server:
  port: 9090

spring:
  application:
    name: oauth-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 85a83d3a-f2af-4927-b4f8-a713ae88814f
  redis:
    host: 127.0.0.1
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"
# logging:
#   level: debug
#     config: classpath:logback.xml